org.gradle.jvmargs=-Xmx32G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.07

# Environment Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.1, 1.22,)
neo_version=21.4.20-beta
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod Properties
mod_id=gadget_lab
mod_name=Gadget Lab
mod_license=All Rights Reserved
mod_version=1.0.7
mod_group_id=nicusha.gadget_lab
mod_authors=Nicusha
mod_description=Gadget Lab is a Minecraft mod that adds a variety of random items to enhance gameplay, offering conveniences and improvements to your Minecraft experience.

## Dependency Properties
cloth_version=17.0.144
architectury_version=15.0.1
rei_version=18.0.796
jei_version=19.8.5.118