org.gradle.jvmargs=-Xmx16G
org.gradle.daemon=false


## Environment Properties
minecraft_version=1.20.4
minecraft_version_range=[1.20.4,1.21)
forge_version=49.0.38
forge_version_range=[0,)
loader_version_range=[0,)
mapping_channel=official
mapping_version=1.20.4

## Mod Properties
mod_id=gadget_lab
mod_name=Gadget Lab
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=nicusha.gadget_lab
mod_authors=Nicusha
mod_description=Gadget Lab is a Minecraft mod that adds a variety of random items to enhance gameplay, offering conveniences and improvements to your Minecraft experience.

## Dependency Properties
jei_version=17.3.0.49
curios_version=7.3.4+1.20.4