modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/NicosaurusRex99/Gadget-Lab/issues"

[[mods]]
modId="gadget_lab"
version="1.0.2"
displayName="Gadget Lab"
updateJSONURL="https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/main/gadget_lab_update.json"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/gadget-lab"
logoFile="gadget_lab.png"
authors="${mod_authors}"
description='''${mod_description}'''


[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.gadget_lab]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"