modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/NicosaurusRex99/Gadget-Lab/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/NicosaurusRex99/Nicusha-mod-assets/main/gadget_lab_update.json"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/gadget-lab"
logoFile="gadget_lab.png"
authors="Nicusha"
description='''Gadget Lab is a Minecraft mod that adds a variety of random items to enhance gameplay, offering conveniences and improvements to your Minecraft experience.'''


[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.gadget_lab]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"